# Generated by Django 4.2.24 on 2025-09-30 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('stage', models.CharField(max_length=100, verbose_name='stage')),
                ('branch', models.CharField(max_length=100, verbose_name='branch')),
                ('rank', models.CharField(max_length=100, verbose_name='rank')),
                ('experience', models.IntegerField(verbose_name='experience')),
                ('fragments', models.IntegerField(verbose_name='fragments')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='TableSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('value', models.CharField(max_length=100, verbose_name='value')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.mission')),
            ],
        ),
        migrations.CreateModel(
            name='TableMissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependentMissions', models.CharField(max_length=100, verbose_name='dependentMissions')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='users.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт')),
                ('money', models.IntegerField(default=0, verbose_name='Деньги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
